// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyMGSHK35Qqyn_y8-RkzGcxu9KBbWwmro',
    appId: '1:115601549489:web:7cb04a0d53282631cd9a90',
    messagingSenderId: '115601549489',
    projectId: 'appaluno-8a77b',
    authDomain: 'appaluno-8a77b.firebaseapp.com',
    storageBucket: 'appaluno-8a77b.firebasestorage.app',
    measurementId: 'G-Q3HCSCSRG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyaQrKuD5yyCDkSkDQzIcErYVGQgbTZHc',
    appId: '1:115601549489:android:4eeee3f19fbc292acd9a90',
    messagingSenderId: '115601549489',
    projectId: 'appaluno-8a77b',
    storageBucket: 'appaluno-8a77b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAexZNRWhsw9KsVjPqoI0cioxvitOrus2g',
    appId: '1:115601549489:ios:e70b0e5d309f6be2cd9a90',
    messagingSenderId: '115601549489',
    projectId: 'appaluno-8a77b',
    storageBucket: 'appaluno-8a77b.firebasestorage.app',
    iosBundleId: 'com.example.appAluno',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAexZNRWhsw9KsVjPqoI0cioxvitOrus2g',
    appId: '1:115601549489:ios:e70b0e5d309f6be2cd9a90',
    messagingSenderId: '115601549489',
    projectId: 'appaluno-8a77b',
    storageBucket: 'appaluno-8a77b.firebasestorage.app',
    iosBundleId: 'com.example.appAluno',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyMGSHK35Qqyn_y8-RkzGcxu9KBbWwmro',
    appId: '1:115601549489:web:d8b441b1b14f986fcd9a90',
    messagingSenderId: '115601549489',
    projectId: 'appaluno-8a77b',
    authDomain: 'appaluno-8a77b.firebaseapp.com',
    storageBucket: 'appaluno-8a77b.firebasestorage.app',
    measurementId: 'G-YMSSJBTR6V',
  );

}